add_subdirectory(mech_eye)
add_subdirectory(orbbec_gemini)
add_subdirectory(livox_mid360)
add_subdirectory(tfmini_plus)
add_subdirectory(vision)
if(SCAN_TRACKING_ENABLE_LB_POSE_DETECTION)
    add_subdirectory(tracking)
endif()
add_subdirectory(modbus)
add_subdirectory(flow_control)
add_subdirectory(hmi_server)
